import spacy

# Load model
nlp = spacy.load("modelo_juridico")

# Exemplo de uso do modelo
text = """PEDIDO DE UNIFORMIZAÇÃO NACIONAL. PETIÇÃO DE CHAMAMENTO DO FEITO À ORDEM RECEBIDA COMO AGRAVO INTERNO. 
ERRO DE AUTUAÇÃO EXISTENTE DESDE O DESPACHO DA PETIÇÃO INICIAL. AÇÃO PROPOSTA EM FACE DO INSS EM QUE FIGUROU COMO 
PARTE NA AUTUAÇÃO A UNIÃO. AUSÊNCIA DE PARTICIPAÇÃO DO INSS NA RELAÇÃO PROCESSUAL. DIVERSAS PETIÇÕES DA UNIÃO 
ALERTANDO PARA O ERRO DE AUTUAÇÃO. DECISÃO DESTA RELATORIA QUE, TAMBÉM SEM OBSERVAR REFERIDO ERRO DE AUTUAÇÃO, 
DEU PROVIMENTO AO PEDIDO DE UNIFORMIZAÇÃO DO AUTOR. NULIDADE CONFIGURADA DESDE O DESPACHO DA INICIAL. ANULAÇÃO 
DO PROCESSO DESDE O DESPACHO DA PETIÇÃO INICIAL. AGRAVO INTERNO CONHECIDO E PROVIDO."""
doc = nlp(text)

print(doc.ents)

for ent in doc.ents:
    print(ent.text, ent.label_)
